import { AircraftSpec, MissileType, GroundUnitType } from "../types/game";

export const AIRCRAFT_SPECS: Record<string, AircraftSpec> = {
  "F-16C": {
    model: "F-16C Viper",
    role: "Multi-role",
    rcsFrontal: 1.0,
    rcsLateral: 5.0,
    maxSpeedMach: 2.0,
    radarRangeKm: 110,
    fuelCapacityL: 3200,
    fuelConsumptionBase: 35,
    ecmStrength: 0.3,
    flaresCapacity: 30,
    countermeasuresCapacity: 30,
    missileCapacity: { "AIM-120C": 6, "AIM-9X": 2 },
    gunAmmo: 500,
  },
  "Gripen": {
    model: "JAS 39 Gripen",
    role: "Interceptor",
    rcsFrontal: 0.1,
    rcsLateral: 1.5,
    maxSpeedMach: 2.0,
    radarRangeKm: 120,
    fuelCapacityL: 2300,
    fuelConsumptionBase: 28,
    ecmStrength: 0.5,
    flaresCapacity: 40,
    countermeasuresCapacity: 40,
    missileCapacity: { "Meteor": 4, "IRIS-T": 2 },
    gunAmmo: 120,
  },
  "Su-27": {
    model: "Su-27 Flanker",
    role: "Superiority",
    rcsFrontal: 15.0,
    rcsLateral: 25.0,
    maxSpeedMach: 2.35,
    radarRangeKm: 150,
    fuelCapacityL: 9400,
    fuelConsumptionBase: 60,
    ecmStrength: 0.2,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: { "R-77": 6, "R-73": 4 },
    gunAmmo: 150,
  },
  "MiG-29": {
    model: "MiG-29 Fulcrum",
    role: "Interceptor",
    rcsFrontal: 5.0,
    rcsLateral: 12.0,
    maxSpeedMach: 2.25,
    radarRangeKm: 80,
    fuelCapacityL: 3500,
    fuelConsumptionBase: 45,
    ecmStrength: 0.2,
    flaresCapacity: 30,
    countermeasuresCapacity: 30,
    missileCapacity: { "R-77": 2, "R-73": 4 },
    gunAmmo: 150,
  },
  "F-35A": {
    model: "F-35A Lightning II",
    role: "Stealth",
    rcsFrontal: 0.001,
    rcsLateral: 0.01,
    maxSpeedMach: 1.6,
    radarRangeKm: 160,
    fuelCapacityL: 8300,
    fuelConsumptionBase: 75,
    ecmStrength: 0.8,
    flaresCapacity: 24,
    countermeasuresCapacity: 24,
    missileCapacity: { "AIM-120D": 4 },
    gunAmmo: 180,
  },
  "C-130": {
    model: "C-130 Hercules",
    role: "Transport",
    rcsFrontal: 80.0,
    rcsLateral: 120.0,
    maxSpeedMach: 0.6,
    radarRangeKm: 40,
    fuelCapacityL: 25000,
    fuelConsumptionBase: 50,
    ecmStrength: 0.1,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "B-2": {
    model: "B-2 Spirit",
    role: "Stealth Bomber",
    rcsFrontal: 0.0001,
    rcsLateral: 0.001,
    maxSpeedMach: 0.95,
    radarRangeKm: 150,
    fuelCapacityL: 75000,
    fuelConsumptionBase: 120,
    ecmStrength: 0.9,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: { "BVR": 16, "Dogfight": 8 },
    gunAmmo: 0,
  },
  "B-1B": {
    model: "B-1B Lancer",
    role: "Supersonic Bomber",
    rcsFrontal: 1.0,
    rcsLateral: 10.0,
    maxSpeedMach: 1.25,
    radarRangeKm: 120,
    fuelCapacityL: 88000,
    fuelConsumptionBase: 150,
    ecmStrength: 0.4,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "B-52H": {
    model: "B-52H Stratofortress",
    role: "Heavy Bomber",
    rcsFrontal: 100.0,
    rcsLateral: 200.0,
    maxSpeedMach: 0.84,
    radarRangeKm: 100,
    fuelCapacityL: 180000,
    fuelConsumptionBase: 200,
    ecmStrength: 0.3,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "Tu-160": {
    model: "Tu-160 White Swan",
    role: "Supersonic Bomber",
    rcsFrontal: 15.0,
    rcsLateral: 50.0,
    maxSpeedMach: 2.05,
    radarRangeKm: 140,
    fuelCapacityL: 148000,
    fuelConsumptionBase: 180,
    ecmStrength: 0.3,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: { "BVR": 12, "Dogfight": 4 },
    gunAmmo: 0,
  },
  "H-6K": {
    model: "H-6K",
    role: "Strategic Bomber",
    rcsFrontal: 40.0,
    rcsLateral: 80.0,
    maxSpeedMach: 0.85,
    radarRangeKm: 120,
    fuelCapacityL: 40000,
    fuelConsumptionBase: 100,
    ecmStrength: 0.2,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "C-5M": {
    model: "C-5M Galaxy",
    role: "Strategic Cargo",
    rcsFrontal: 150.0,
    rcsLateral: 300.0,
    maxSpeedMach: 0.79,
    radarRangeKm: 50,
    fuelCapacityL: 190000,
    fuelConsumptionBase: 250,
    ecmStrength: 0.1,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "C-17": {
    model: "C-17 Globemaster III",
    role: "Strategic/Tactical Cargo",
    rcsFrontal: 60.0,
    rcsLateral: 120.0,
    maxSpeedMach: 0.77,
    radarRangeKm: 60,
    fuelCapacityL: 100000,
    fuelConsumptionBase: 150,
    ecmStrength: 0.2,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "An-124": {
    model: "An-124 Ruslan",
    role: "Heavy Strategic Cargo",
    rcsFrontal: 200.0,
    rcsLateral: 400.0,
    maxSpeedMach: 0.7,
    radarRangeKm: 50,
    fuelCapacityL: 210000,
    fuelConsumptionBase: 300,
    ecmStrength: 0.1,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "KC-390": {
    model: "KC-390 Millennium",
    role: "Tactical Transport",
    rcsFrontal: 30.0,
    rcsLateral: 60.0,
    maxSpeedMach: 0.8,
    radarRangeKm: 70,
    fuelCapacityL: 35000,
    fuelConsumptionBase: 80,
    ecmStrength: 0.3,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "B-21": {
    model: "B-21 Raider",
    role: "Next-Gen Stealth Bomber",
    rcsFrontal: 0.00005,
    rcsLateral: 0.0005,
    maxSpeedMach: 0.9,
    radarRangeKm: 180,
    fuelCapacityL: 70000,
    fuelConsumptionBase: 110,
    ecmStrength: 0.95,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "Tu-22M3M": {
    model: "Tu-22M3M Backfire",
    role: "Long-range Bomber",
    rcsFrontal: 10.0,
    rcsLateral: 40.0,
    maxSpeedMach: 1.88,
    radarRangeKm: 120,
    fuelCapacityL: 54000,
    fuelConsumptionBase: 140,
    ecmStrength: 0.3,
    flaresCapacity: 60,
    countermeasuresCapacity: 60,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "PAK-DA": {
    model: "Tupolev PAK DA",
    role: "Stealth Bomber",
    rcsFrontal: 0.001,
    rcsLateral: 0.01,
    maxSpeedMach: 0.9,
    radarRangeKm: 160,
    fuelCapacityL: 80000,
    fuelConsumptionBase: 130,
    ecmStrength: 0.8,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "H-20": {
    model: "Xian H-20",
    role: "Stealth Bomber",
    rcsFrontal: 0.001,
    rcsLateral: 0.01,
    maxSpeedMach: 0.9,
    radarRangeKm: 150,
    fuelCapacityL: 70000,
    fuelConsumptionBase: 120,
    ecmStrength: 0.8,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "A400M": {
    model: "Airbus A400M Atlas",
    role: "Tactical/Strategic Transport",
    rcsFrontal: 40.0,
    rcsLateral: 80.0,
    maxSpeedMach: 0.72,
    radarRangeKm: 70,
    fuelCapacityL: 50000,
    fuelConsumptionBase: 100,
    ecmStrength: 0.3,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  },
  "Y-20": {
    model: "Xian Y-20",
    role: "Heavy Transport",
    rcsFrontal: 100.0,
    rcsLateral: 200.0,
    maxSpeedMach: 0.75,
    radarRangeKm: 60,
    fuelCapacityL: 110000,
    fuelConsumptionBase: 160,
    ecmStrength: 0.2,
    flaresCapacity: 120,
    countermeasuresCapacity: 120,
    missileCapacity: {},
    gunAmmo: 0,
  }
};

export const GROUND_UNIT_SPECS = {
  "S-400": {
    model: "S-400 Triumf",
    type: GroundUnitType.SAM_BATTERY,
    radarRangeKm: 400,
    missileCapacity: { "48N6E3": 48 },
    health: 100,
    speedKmH: 60
  },
  "PATRIOT": {
    model: "MIM-104 Patriot",
    type: GroundUnitType.SAM_BATTERY,
    radarRangeKm: 160,
    missileCapacity: { "PAC-3": 16 },
    health: 100,
    speedKmH: 60
  },
  "S-300": {
    model: "S-300V Antey",
    type: GroundUnitType.SAM_BATTERY,
    radarRangeKm: 300,
    missileCapacity: { "5V55R": 32 },
    health: 100,
    speedKmH: 50
  },
  "THAAD": {
    model: "THAAD",
    type: GroundUnitType.SAM_BATTERY,
    radarRangeKm: 200,
    missileCapacity: { "THAD": 8 },
    health: 100,
    speedKmH: 80
  },
  "AEGIS": {
    model: "Aegis Ashore",
    type: GroundUnitType.SAM_BATTERY,
    radarRangeKm: 500,
    missileCapacity: { "SM-6": 48, "SM-3": 24 },
    health: 120,
    speedKmH: 0
  },
  "AN-TPY2": {
    model: "AN-TPY-2",
    type: GroundUnitType.RADAR_STATION,
    radarRangeKm: 600,
    missileCapacity: {},
    health: 80,
    speedKmH: 0
  },
  "GEPARD": {
    model: "Gepard",
    type: GroundUnitType.AAA,
    radarRangeKm: 15,
    missileCapacity: {},
    health: 60,
    speedKmH: 65
  },
  "M2_BRADLEY": {
    model: "M2 Bradley",
    type: GroundUnitType.APC,
    radarRangeKm: 10,
    missileCapacity: { "TOW": 2 },
    health: 80,
    speedKmH: 66
  },
  "M1_ABRAMS": {
    model: "M1A2 Abrams",
    type: GroundUnitType.TANK,
    radarRangeKm: 12,
    missileCapacity: {},
    health: 150,
    speedKmH: 67
  },
  "T-90": {
    model: "T-90MS",
    type: GroundUnitType.TANK,
    radarRangeKm: 10,
    missileCapacity: { "Reflex": 4 },
    health: 140,
    speedKmH: 60
  },
  "LEOPARD2": {
    model: "Leopard 2A7+",
    type: GroundUnitType.TANK,
    radarRangeKm: 12,
    missileCapacity: {},
    health: 145,
    speedKmH: 68
  },
  "M109": {
    model: "M109A7 Paladin",
    type: GroundUnitType.ARTILLERY,
    radarRangeKm: 30,
    missileCapacity: {},
    health: 70,
    speedKmH: 56
  },
  "PZH2000": {
    model: "PZH 2000",
    type: GroundUnitType.ARTILLERY,
    radarRangeKm: 30,
    missileCapacity: {},
    health: 75,
    speedKmH: 60
  },
  "BM-30": {
    model: "BM-30 Smerch",
    type: GroundUnitType.ARTILLERY,
    radarRangeKm: 40,
    missileCapacity: { "9M55K": 12 },
    health: 80,
    speedKmH: 50
  },
  "ATACMS": {
    model: "ATACMS",
    type: GroundUnitType.ARTILLERY,
    radarRangeKm: 50,
    missileCapacity: { "ATACMS": 1 },
    health: 60,
    speedKmH: 60
  },
  "BRADLEY": {
    model: "M3 Bradley",
    type: GroundUnitType.RECON,
    radarRangeKm: 20,
    missileCapacity: { "TOW": 2 },
    health: 70,
    speedKmH: 66
  },
  "M113": {
    model: "M113A3",
    type: GroundUnitType.APC,
    radarRangeKm: 8,
    missileCapacity: {},
    health: 55,
    speedKmH: 64
  },
  "HMMWV": {
    model: "M1151 HMMWV",
    type: GroundUnitType.APC,
    radarRangeKm: 5,
    missileCapacity: { "TOW": 1 },
    health: 40,
    speedKmH: 105
  },
  "STRYKER": {
    model: "Stryker ICV",
    type: GroundUnitType.APC,
    radarRangeKm: 12,
    missileCapacity: { "TOW": 2 },
    health: 85,
    speedKmH: 100
  },
  "PATROL": {
    model: "MRAP Patrol",
    type: GroundUnitType.RECON,
    radarRangeKm: 6,
    missileCapacity: {},
    health: 50,
    speedKmH: 110
  }
};

export const MISSILE_SPECS = {
  "AIM-120C": {
    model: "AIM-120C-5",
    type: MissileType.MEDIUM_RANGE,
    rangeMax: 105,
    nez: 25,
    speed: 4.0,
    cost: 2500,
    reloadTime: 10
  },
  "Meteor": {
    model: "MBDA Meteor",
    type: MissileType.LONG_RANGE,
    rangeMax: 200,
    nez: 60,
    speed: 4.0,
    cost: 5000,
    reloadTime: 15
  },
  "AIM-9X": {
    model: "AIM-9X Sidewinder",
    type: MissileType.SHORT_RANGE,
    rangeMax: 20,
    nez: 5,
    speed: 3.0,
    cost: 1000,
    reloadTime: 5
  },
  "R-77": {
    model: "R-77 Adder",
    type: MissileType.MEDIUM_RANGE,
    rangeMax: 80,
    nez: 20,
    speed: 4.0,
    cost: 2000,
    reloadTime: 10
  },
  "R-73": {
    model: "R-73 Archer",
    type: MissileType.SHORT_RANGE,
    rangeMax: 30,
    nez: 8,
    speed: 2.5,
    cost: 1200,
    reloadTime: 5
  },
  "48N6E3": {
    model: "48N6E3",
    type: MissileType.LONG_RANGE,
    rangeMax: 250,
    nez: 80,
    speed: 6.0,
    cost: 8000,
    reloadTime: 15
  },
  "PAC-3": {
    model: "PAC-3 MSE",
    type: MissileType.LONG_RANGE,
    rangeMax: 120,
    nez: 40,
    speed: 5.0,
    cost: 6000,
    reloadTime: 15
  }
};
